test_data = [
            {
                'category':'Training',
                'isVisible':False,
                'folders':[
                    {
                        'folder':'Training',
                    },
                    {
                        'folder':'Excel',
                    }
                ],
            },
            {
                'category':'Training',
                'isVisible':False,
                'folders':[
                    {
                        'folder':'Training',
                    },
                    {
                        'folder':'Excel',
                    }
                ],
            },
            {
                'category':'Training',
                'isVisible':False,
                'folders':[
                    {
                        'folder':'Training',
                    },
                    {
                        'folder':'Excel',
                    }
                ],
            }
        ]